### ISSUE TITLE
1.0 roadmap

### ISSUE THREAD

**Issue by egoist** [egoist/codepan#62]
- [ ] New UI 🤔
- [ ] Prettier support
- [ ] [Monaco editor](https://github.com/Microsoft/monaco-editor/blob/master/gulpfile.js)?
- [ ] Save as readable gist
- [ ] New project name / domain name
